services:
  # Service backend pour Django
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    command: ["./wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend/app:/home/django/app
      - ./frontend:/home/django/app/frontend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network

  # Service base de données PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # (Optionnel) Un service pour gérer les migrations Django, exécute les migrations de la base de données
  migrate:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: django_migrate
    command: >
      bash -c "./wait-for-db.sh && 
               python manage.py makemigrations && 
               python manage.py migrate"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge